
version: '3.7'

services:
    app:
        image: syndya:latest
        build:
            context: ..
            dockerfile: deployments/deployment.Dockerfile
        environment:
            LISTEN_HOST: 0.0.0.0
            LISTEN_PORT: 8080
            GIN_MODE: debug
            METADATAS_LIST: rating
        ports:
            - 8080:8080
